### ISSUE TITLE
希望把Redis客户端换成CSRedis的

### ISSUE THREAD

**Issue by 5653325** [sonosun/EasyVerificationCode#1]
希望把Redis客户端换成CSRedis的

**Comment by sonosun** [comment]
> 希望把Redis客户端换成CSRedis的
如果有需要，可以扩展一下，只需三步：
1.用CSRedis实现接口IVerificationCodeStore。
2.修改ServiceCollectionExtension中服务注册，将自己新增的服务，注册到IVerificationCodeStore接口。
3.移除对StackExchange.Redis的引用（保留应该也无妨）。
